version: '{build}'

image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: LJxMxZl1dCKgMF5FlErnwQ==
  DOCKER_PASS:
    secure: HASfuLeqW86zydzpb7/5Zg==
  DOCKER_IMAGE_NAME: idubnori/eventstore:4.1.1-hotfix1-windowsservercore

init:
  - ps: docker version
  - ps: docker info
  - ps: docker images
  - ps: |
      cinst curl -y --no-progress
      sal curl (Join-Path $env:ChocolateyInstall "bin\curl.exe") -O AllScope

build_script:
  - ps: |
      cd $env:APPVEYOR_BUILD_FOLDER
      cd .\windowsservercore
      docker build -t $env:DOCKER_IMAGE_NAME .
      docker images

test_script:
  - ps: |
      $cid = docker run -d $env:DOCKER_IMAGE_NAME
      $hostip = docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" $cid
      Start-Sleep -s 15
      curl "http://${hostip}:2113" -s -f --connect-timeout 30
      Test-NetConnection -Port 1113 -ComputerName ${hostip} -InformationLevel "Detailed"

# deploy_script:
#   - ps: |
#       echo $env:DOCKER_PASS | docker login -u $env:DOCKER_USER --password-stdin
#       docker push $env:DOCKER_IMAGE_NAME